### ISSUE TITLE
API

### ISSUE THREAD

**Issue by CBIhalsen** [frolvanya/ai-humanizer#1]
Hello, is it convenient to disclose which external api to use?

**Comment by frolvanya** [comment]
I didn't quite understand your question. As you can see from the code, I'm using the API from https://aitohumanconverter.com. Have I answered your question?

**Comment by CBIhalsen** [comment]
> I didn't quite understand your question. As you can see from the code, I'm using the API from https://aitohumanconverter.com. Have I answered your question?

Thank you for your reply. Did you develop this target website? I have been looking for a specific approach to ai humanize because I lack experience with transformer models.

**Comment by frolvanya** [comment]
Nope, I was using primarily because it's free
