### ISSUE TITLE
How to use it? Is there any API similar to GPT related models?

### ISSUE THREAD

**Issue by draftgo** [frolvanya/ai-humanizer#2]
How to use it? Is there any API similar to GPT related models?

**Comment by frolvanya** [comment]
Unfortunately, they have changed API, so it's no longer active. It was just a small project to make an extension for Raycast, so I'm not sure if I'll spend my time fixing it

Yes, there're some API's (just google "ai humanizer"), but mostly they're not free

**Comment by draftgo** [comment]
I'm from China, and I want to solve the problem of AIGC testing. Do you have any recommendations?

**Comment by frolvanya** [comment]
Nope, as you can see from my repos, I'm not very interested in AI, so I can't give you any advice
