### ISSUE TITLE
Update the API

### ISSUE THREAD

**Issue by rephrasyai** [frolvanya/ai-humanizer#3]
Hi there, 

we'd like to make a small change to allow people to use our [Humanizer API](https://www.rephrasy.ai/api-solution)?

Let me know if we can proceed,
Chrisi

**Comment by frolvanya** [comment]
Sure, let's do it

**Comment by rephrasyai** [comment]
Hi, opened a PR in #4 

Hope everything is alright!

Thanks so much.

**Comment by frolvanya** [comment]
Thanks for your contribution! I've created PR to update an extension on raycast's side, so now it will take around 5 business days to merge it

https://github.com/raycast/extensions/pull/15383

**Comment by frolvanya** [comment]
Small update, it was merged already. @rephrasyai your product looks great, is it possible to get some sort of dev api key for myself that would have small amount of credits for free?

**Comment by rephrasyai** [comment]
definitely, just ping support@rephrasy.ai with your e-mail and we set that up for you! 

Thanks a bunch

**Comment by frolvanya** [comment]
> just ping [support@rephrasy.ai](mailto:support@rephrasy.ai)

Done, thank you so much :heart:
